name: dotnet env file

on:
  workflow_dispatch:
  
env:
  AZURE_FUNCTION_PROJ_PATH: src/FunctionApp  # set this to the path to your function app project
  ROOT_SOLUTION_PATH: src # set this to the root path of your solution/project file
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}  # Azure subscription ID stored in GitHub secrets
  REGION: 'australiaeast'
  DOTNET_VERSION: '8.x'  # Specify your .NET SDK version
  APP_NAME: 'github-poc'  # Replace with your Azure Resource Group name

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Set env
        run: echo "RESOURCE_GROUP_NAME=${{ env.APP_NAME }}-${{ vars.ENVIRONMENT }}" >> $GITHUB_ENV
      
      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_FUNCTION_APP }}
    
      - name: Get the latest source code commit
        uses: actions/checkout@v2        
        
        
      - name: 'Load .env file'
      uses: falti/dotenv-action@v1.1.4
      with:
        path: ./env/dev.env

      - name: 'Echo'
        run: echo ${{ steps.dotenv.outputs.Note }}
  
    build:
    runs-on: ubuntu-latest
    environment: uat
    steps:

      - name: Set env
        run: echo "RESOURCE_GROUP_NAME=${{ env.APP_NAME }}-${{ vars.ENVIRONMENT }}" >> $GITHUB_ENV
      
      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_FUNCTION_APP }}
    
      - name: Get the latest source code commit
        uses: actions/checkout@v2        
        
        
      - name: 'Load .env file'
      uses: falti/dotenv-action@v1.1.4
      with:
        path: ./env/${{ vars.ENVIRONMENT }}.env

      - name: 'Echo'
        run: echo ${{ steps.dotenv.outputs.Note }}
        